sudo: required
services:
  - docker

before_install:
  - docker build -t jimboyoo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jimboyoo/react-test npm test

after_success:
  - docker build -t jimboyoo/fib-client ./client
  - docker build -t jimboyoo/fib-nginx ./nginx
  - docker build -t jimboyoo/fib-server ./server
  - docker build -t jimboyoo/fib-worker ./worker
  #Log into docker CLI (credentials stored on Travis as env variables)
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin 
  #Take these images and push to Docker hub
  - docker push jimboyoo/fib-client
  - docker push jimboyoo/fib-nginx
  - docker push jimboyoo/fib-server
  - docker push jimboyoo/fib-worker
